name: deploy latest pdf
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: complie TeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
      - name: deploy pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: new pdfs
          branch: gh-pages
